CREATE TABLE post (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255),
  content TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  author VARCHAR(255)
);

CREATE TABLE comment (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  content TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  author VARCHAR(255),
  post_id BIGINT UNSIGNED,
  parent_id BIGINT UNSIGNED,
  FOREIGN KEY (post_id) REFERENCES post(id),
  FOREIGN KEY (parent_id) REFERENCES comment(id)
);
